#!/usr/bin/env node
// PureChain rehearsal load generator / functional client.
//
// One subcommand per campaign operation; every command talks plain JSON-RPC or
// ethers v6 against the in-network node names (http://nodeN:8545) and writes
// its evidence as CSV/JSON under /artifacts.
//
// Free-gas network: every tx goes out with gasPrice 0, type-0, chainId
// 424242 — the shape real users produce.

const { ethers } = require("ethers");
const fs = require("fs");

const CHAIN_ID = 424242n;
const ART = "/artifacts";
// Faucet = hardhat account 4. Funded in genesis; never a validator.
const FAUCET_KEY = "0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a";

// Deterministic nodekeys for node1..node6 (arbitrary fixed scalars — test-only).
const NODEKEYS = [
  "a1b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeef001",
  "a1b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeef002",
  "a1b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeef003",
  "a1b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeef004",
  "a1b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeef005",
  "a1b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeef006",
];

// Minimal hand-assembled contract (no compiler dependency):
//   on any call with >=36 bytes calldata: storage[0] = calldata[4:36],
//   LOG1(topic=TOPIC, data=value), returns storage[0].
const TOPIC = "0x72656865617273616c2d6576656e742d72656865617273616c2d6576656e7421";
const RUNTIME = "60043580600055600052" + "7f" + TOPIC.slice(2) + "60206000a1" + "600054600052" + "60206000f3";
const DEPLOY = "0x603b600c600039603b6000f3" + RUNTIME;

function provider(rpc) {
  return new ethers.JsonRpcProvider(rpc, { chainId: Number(CHAIN_ID), name: "purechain" }, { staticNetwork: true, polling: true, pollingInterval: 250 });
}
function now() { return Date.now(); }
function log(...a) { console.log(new Date().toISOString(), ...a); }
function append(file, line) { fs.appendFileSync(`${ART}/${file}`, line + "\n"); }
function pct(sorted, p) { return sorted.length ? sorted[Math.min(sorted.length - 1, Math.round((sorted.length - 1) * p))] : -1; }
function summarize(tag, lat) {
  const s = [...lat].sort((a, b) => a - b);
  const out = { tag, n: s.length, median: pct(s, 0.5), p95: pct(s, 0.95), mean: s.length ? Math.round(s.reduce((a, b) => a + b, 0) / s.length) : -1 };
  log(`SUMMARY ${tag}: n=${out.n} median=${out.median}ms mean=${out.mean}ms p95=${out.p95}ms`);
  append("summaries.jsonl", JSON.stringify({ ts: new Date().toISOString(), ...out }));
  return out;
}
async function sendRaw(rpc, hex) {
  const r = await fetch(rpc, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "eth_sendRawTransaction", params: [hex] }) });
  const j = await r.json();
  if (j.error) throw new Error(j.error.message);
  return j.result;
}
async function rpcCall(rpc, method, params = []) {
  const r = await fetch(rpc, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }) });
  const j = await r.json();
  if (j.error) throw new Error(`${method}: ${j.error.message}`);
  return j.result;
}
function loadWallets() { return JSON.parse(fs.readFileSync(`${ART}/wallets.json`, "utf8")).map(k => new ethers.Wallet(k)); }
// Concurrent commands MUST NOT share accounts, or they race each other's
// nonces (a background steady load + a relaycheck on the same wallet produced
// an instant false "relay DEAD"). Partition: steady/ramp 0-7, latency 8,
// contract 9, relaycheck 11.
function loadPartition() { return loadWallets().slice(0, 8); }
function walletFor(role) { const w = loadWallets(); return { latency: w[8], contract: w[9], relay: w[11] }[role]; }
async function signedTransfer(wallet, nonce, to, value = 1n) {
  return wallet.signTransaction({ type: 0, chainId: CHAIN_ID, nonce, gasPrice: 0, gasLimit: 21000, to, value });
}

// ---------------------------------------------------------------- commands --

// keygen: write deterministic nodekeys into each node's datadir and generate
// scripts/addpeers.js with the derived enodes (the static-peering shape).
async function keygen() {
  let js = "// GENERATED by loadgen keygen — rehearsal counterpart of the deployment addpeers.js\n";
  NODEKEYS.forEach((k, i) => {
    const pub = ethers.SigningKey.computePublicKey("0x" + k, false).slice(4); // strip 0x04
    fs.mkdirSync(`/hostdata/node${i + 1}/geth`, { recursive: true });
    fs.writeFileSync(`/hostdata/node${i + 1}/geth/nodekey`, k);
    js += `admin.addPeer("enode://${pub}@node${i + 1}:30303");\n`;
  });
  js += 'console.log("Added all peers. Current peer count: " + admin.peers.length);\n';
  fs.writeFileSync("/scripts/addpeers.js", js);
  log("nodekeys written for node1..6; scripts/addpeers.js generated");
}

// fund <n>: create n throwaway wallets, fund each from the faucet.
async function fund(rpc, n) {
  const p = provider(rpc);
  const faucet = new ethers.Wallet(FAUCET_KEY, p);
  const wallets = Array.from({ length: n }, () => ethers.Wallet.createRandom());
  fs.writeFileSync(`${ART}/wallets.json`, JSON.stringify(wallets.map(w => w.privateKey), null, 1));
  let nonce = await p.getTransactionCount(faucet.address);
  const hashes = [];
  for (const w of wallets) {
    const tx = await faucet.sendTransaction({ type: 0, chainId: CHAIN_ID, nonce: nonce++, gasPrice: 0, gasLimit: 21000, to: w.address, value: ethers.parseEther("1000") });
    hashes.push(tx.hash);
  }
  await p.waitForTransaction(hashes[hashes.length - 1], 1, 120000);
  log(`funded ${n} wallets (last ${hashes[hashes.length - 1]})`);
}

// steady <rpc> <tps> <seconds> <tag> [idleGapSec]: continuous mixed load at a
// target rate. With idleGapSec > 0, alternates 20s bursts with idleGapSec of
// silence — this exercises smart-automine's start/stop transitions, which a
// constant stream never would. Latency measured per-tx (submit -> mined).
async function steady(rpc, tps, seconds, tag, idleGap = 0) {
  const p = provider(rpc);
  const wallets = loadPartition().map(w => w.connect(p));
  // "pending" nonces, never "latest": an aborted earlier run can leave this
  // wallet's txs parked in the pool, and latest-based nonces would collide
  // with every one of them ("already known") until the backlog mines.
  const nonces = await Promise.all(wallets.map(w => p.getTransactionCount(w.address, "pending")));
  const latencies = [];
  const pending = new Map(); // hash -> t0
  let sent = 0, failed = 0, wi = 0;
  const t0 = now();
  const interval = 1000 / tps;
  let burstPhase = true, phaseStart = now();
  const checker = setInterval(async () => {
    for (const [h, ts] of [...pending]) {
      try {
        const r = await rpcCall(rpc, "eth_getTransactionReceipt", [h]);
        if (r && r.blockNumber) {
          const ms = now() - ts;
          latencies.push(ms);
          append(`lat-${tag}.csv`, `${new Date(ts).toISOString()},${h},${ms}`);
          pending.delete(h);
        }
      } catch (e) { /* transient rpc errors tolerated; receipt re-checked next tick */ }
    }
  }, 300);
  while (now() - t0 < seconds * 1000) {
    if (idleGap > 0) {
      const inPhase = (now() - phaseStart) / 1000;
      if (burstPhase && inPhase > 20) { burstPhase = false; phaseStart = now(); log(`idle gap ${idleGap}s (automine should stop)...`); }
      else if (!burstPhase && inPhase > idleGap) { burstPhase = true; phaseStart = now(); log("burst resumes (automine should start)"); }
      if (!burstPhase) { await new Promise(r => setTimeout(r, 500)); continue; }
    }
    const i = wi++ % wallets.length;
    try {
      const raw = await signedTransfer(wallets[i], nonces[i], wallets[(i + 1) % wallets.length].address);
      const h = await sendRaw(rpc, raw);
      nonces[i]++;
      pending.set(h, now());
      sent++;
    } catch (e) {
      failed++;
      if (failed <= 5 || failed % 100 === 0) log(`send error (#${failed}): ${e.message.slice(0, 120)}`);
      if (/nonce/i.test(e.message)) nonces[i] = await p.getTransactionCount(wallets[i].address);
    }
    await new Promise(r => setTimeout(r, interval));
  }
  clearInterval(checker);
  // grace: let stragglers mine
  const graceEnd = now() + 30000;
  while (pending.size && now() < graceEnd) {
    for (const [h, ts] of [...pending]) {
      const r = await rpcCall(rpc, "eth_getTransactionReceipt", [h]).catch(() => null);
      if (r && r.blockNumber) { latencies.push(now() - ts); pending.delete(h); }
    }
    await new Promise(r => setTimeout(r, 500));
  }
  log(`steady done: sent=${sent} failed=${failed} unmined=${pending.size}`);
  const s = summarize(tag, latencies);
  const unminedRatio = sent ? pending.size / sent : 1;
  append("gates.jsonl", JSON.stringify({ tag, sent, failed, unmined: pending.size, unminedRatio, median: s.median }));
  if (unminedRatio > 0.02) { log(`GATE FAIL: ${(unminedRatio * 100).toFixed(1)}% of txs never mined`); process.exit(1); }
}

// latency <rpc> <n> <tag> [--cold]: the external researchers' method — strictly
// sequential submit -> receipt. --cold waits out the automine idle window
// (15s) plus margin before each probe, measuring the idle->first-block path.
async function latency(rpc, n, tag, cold = false) {
  const p = provider(rpc);
  const w = walletFor("latency").connect(p);
  let nonce = await p.getTransactionCount(w.address, "pending");
  const lat = [];
  for (let i = 0; i < n; i++) {
    if (cold) { log(`cold probe ${i + 1}/${n}: waiting 22s for automine idle...`); await new Promise(r => setTimeout(r, 22000)); }
    const raw = await signedTransfer(w, nonce, w.address);
    const t0 = now();
    const h = await sendRaw(rpc, raw);
    nonce++;
    for (;;) {
      const r = await rpcCall(rpc, "eth_getTransactionReceipt", [h]).catch(() => null);
      if (r && r.blockNumber) break;
      if (now() - t0 > 60000) { log(`probe ${i} TIMED OUT`); break; }
      await new Promise(r => setTimeout(r, 50));
    }
    lat.push(now() - t0);
    append(`lat-${tag}.csv`, `${new Date(t0).toISOString()},${h},${lat[lat.length - 1]}`);
  }
  summarize(tag, lat);
}

// ramp <rpc> <startTps> <maxTps> <stepSec>: find the ceiling. Each step raises
// the rate; a step fails when >5% of its txs miss receipts within 10s p95.
async function ramp(rpc, startTps, maxTps, stepSec) {
  const p = provider(rpc);
  const wallets = loadPartition().map(w => w.connect(p));
  const nonces = await Promise.all(wallets.map(w => p.getTransactionCount(w.address, "pending")));
  let ceiling = 0;
  for (let tps = startTps; tps <= maxTps; tps = Math.min(maxTps, tps * 2 === tps ? tps + 25 : Math.round(tps * 1.9)) ) {
    const lat = []; const pend = new Map(); let sent = 0, wi = 0, failed = 0;
    const t0 = now();
    const checker = setInterval(async () => {
      for (const [h, ts] of [...pend]) {
        const r = await rpcCall(rpc, "eth_getTransactionReceipt", [h]).catch(() => null);
        if (r && r.blockNumber) { lat.push(now() - ts); pend.delete(h); }
      }
    }, 250);
    while (now() - t0 < stepSec * 1000) {
      const i = wi++ % wallets.length;
      try {
        const raw = await signedTransfer(wallets[i], nonces[i], wallets[(i + 1) % wallets.length].address);
        const h = await sendRaw(rpc, raw); nonces[i]++; pend.set(h, now()); sent++;
      } catch (e) { failed++; if (/nonce/i.test(e.message)) nonces[i] = await p.getTransactionCount(wallets[i].address); }
      await new Promise(r => setTimeout(r, 1000 / tps));
    }
    await new Promise(r => setTimeout(r, 8000));
    clearInterval(checker);
    const s = [...lat].sort((a, b) => a - b);
    const p95v = pct(s, 0.95);
    const minedRatio = sent ? lat.length / sent : 0;
    log(`ramp step ${tps} tx/s: sent=${sent} mined=${lat.length} (${(minedRatio * 100).toFixed(0)}%) p95=${p95v}ms failedSend=${failed}`);
    append("ramp.csv", `${tps},${sent},${lat.length},${p95v},${failed}`);
    if (minedRatio < 0.95 || p95v > 10000) { log(`saturation at ${tps} tx/s; ceiling = ${ceiling} tx/s`); break; }
    ceiling = tps;
    if (tps === maxTps) break;
  }
  fs.writeFileSync(`${ART}/ceiling.txt`, String(ceiling));
  log(`CEILING: ${ceiling} tx/s sustainable`);
}

// erc20-ish functional check: deploy the hand-assembled contract, write a
// value, verify the event via eth_getLogs and the state via eth_call — all
// through the given (public, eth/net/web3-only) RPC node.
async function contractCheck(rpc, tag) {
  const p = provider(rpc);
  const w = walletFor("contract").connect(p);
  let nonce = await p.getTransactionCount(w.address, "pending");
  const deployRaw = await w.signTransaction({ type: 0, chainId: CHAIN_ID, nonce: nonce++, gasPrice: 0, gasLimit: 300000, data: DEPLOY });
  const dh = await sendRaw(rpc, deployRaw);
  const drc = await p.waitForTransaction(dh, 1, 60000);
  if (!drc || drc.status !== 1) throw new Error("deploy failed");
  const addr = drc.contractAddress;
  const value = "0x" + "42".padStart(64, "0");
  const callData = "0xdeadbeef" + value.slice(2);
  const cRaw = await w.signTransaction({ type: 0, chainId: CHAIN_ID, nonce: nonce++, gasPrice: 0, gasLimit: 100000, to: addr, data: callData });
  const ch = await sendRaw(rpc, cRaw);
  const crc = await p.waitForTransaction(ch, 1, 60000);
  if (!crc || crc.status !== 1) throw new Error("write tx failed");
  const logs = await rpcCall(rpc, "eth_getLogs", [{ fromBlock: "0x0", toBlock: "latest", address: addr, topics: [TOPIC] }]);
  if (!logs.length) throw new Error("event NOT found via eth_getLogs");
  const read = await rpcCall(rpc, "eth_call", [{ to: addr, data: "0xdeadbeef" + "0".repeat(64) }, "latest"]);
  log(`contract ok: addr=${addr} logs=${logs.length} read=${read}`);
  append("gates.jsonl", JSON.stringify({ tag: `contract-${tag}`, addr, logs: logs.length, ok: true }));
}

// watch <rpc> <seconds> <tag>: HTTP polling continuity (what real users do —
// the public nodes expose HTTP only). Records every poll error / stall.
async function watch(rpc, seconds, tag) {
  const t0 = now();
  let last = -1, errors = 0, stalls = 0, polls = 0, maxGapMs = 0, lastChange = now();
  while (now() - t0 < seconds * 1000) {
    try {
      const bn = parseInt(await rpcCall(rpc, "eth_blockNumber"), 16);
      polls++;
      if (bn !== last) { const gap = now() - lastChange; if (last >= 0 && gap > maxGapMs) maxGapMs = gap; last = bn; lastChange = now(); }
    } catch (e) { errors++; append(`watch-${tag}.log`, `${new Date().toISOString()} ERROR ${e.message.slice(0, 100)}`); }
    await new Promise(r => setTimeout(r, 500));
  }
  log(`watch ${tag}: polls=${polls} errors=${errors} maxHeadGap=${Math.round(maxGapMs / 1000)}s`);
  append("gates.jsonl", JSON.stringify({ tag: `watch-${tag}`, polls, errors, maxGapMs }));
}

// relaycheck <rpcOfTarget> <rpcOfWitness> <tag>: prove the TARGET node
// gossips transactions (the silent-failure mode after restarts). A tx is
// submitted ONLY to the target; success = the WITNESS node sees it (pending
// or mined) within 25s. Strict for non-mining nodes; for a validator, the
// driver stops its automine+miner first so it cannot self-mine a false pass.
async function relaycheck(rpcTarget, rpcWitness, tag) {
  const p = provider(rpcTarget);
  const w = walletFor("relay").connect(p);
  // Transient submit errors (node just restarted, nonce raced) must not be
  // reported as a dead relay — retry the SUBMIT; only the 25s witness window
  // below decides relay health.
  let h = null, lastErr = null;
  for (let attempt = 0; attempt < 4 && !h; attempt++) {
    try {
      const nonce = await p.getTransactionCount(w.address, "pending");
      const raw = await signedTransfer(w, nonce, w.address);
      h = await sendRaw(rpcTarget, raw);
    } catch (e) {
      lastErr = e;
      log(`relaycheck submit retry ${attempt + 1}: ${e.message.slice(0, 100)}`);
      await new Promise(r => setTimeout(r, 2000));
    }
  }
  if (!h) { log(`RELAY CHECK BROKEN (${tag}): submit never succeeded: ${lastErr && lastErr.message}`); append("gates.jsonl", JSON.stringify({ tag: `relay-${tag}`, ok: false, submitFailed: true })); process.exit(1); }
  const t0 = now();
  for (;;) {
    const seen = await rpcCall(rpcWitness, "eth_getTransactionByHash", [h]).catch(() => null);
    if (seen) { log(`RELAY OK (${tag}): witness saw ${h} after ${now() - t0}ms`); append("gates.jsonl", JSON.stringify({ tag: `relay-${tag}`, ok: true, ms: now() - t0 })); return; }
    if (now() - t0 > 25000) { log(`RELAY DEAD (${tag}): witness never saw ${h}`); append("gates.jsonl", JSON.stringify({ tag: `relay-${tag}`, ok: false })); process.exit(1); }
    await new Promise(r => setTimeout(r, 500));
  }
}

// -------------------------------------------------------------------- main --
(async () => {
  const [cmd, ...a] = process.argv.slice(2);
  try {
    if (cmd === "keygen") await keygen();
    else if (cmd === "fund") await fund(a[0], parseInt(a[1] || "10"));
    else if (cmd === "steady") await steady(a[0], parseFloat(a[1]), parseInt(a[2]), a[3], parseInt(a[4] || "0"));
    else if (cmd === "latency") await latency(a[0], parseInt(a[1]), a[2], a.includes("--cold"));
    else if (cmd === "ramp") await ramp(a[0], parseInt(a[1]), parseInt(a[2]), parseInt(a[3]));
    else if (cmd === "contract") await contractCheck(a[0], a[1] || "check");
    else if (cmd === "watch") await watch(a[0], parseInt(a[1]), a[2]);
    else if (cmd === "relaycheck") await relaycheck(a[0], a[1], a[2]);
    else { console.error("unknown command", cmd); process.exit(2); }
    process.exit(0);
  } catch (e) {
    console.error("FATAL", cmd, e.message);
    process.exit(1);
  }
})();
